### ISSUE TITLE
Hyperlink sourcecode to definitions

### ISSUE THREAD

**Issue by opoudjis** [lutaml/expressir#54]
This is an issue that I have no idea how it is going to be addressed, and it will likely need contributions from both of you.

In ISO 10303, source code is annotated with hyperlinks to the definitions of the keywords being used:

<img width="1083" alt="Στιγμιότυπο 2021-01-22, 00 29 52" src="https://user-images.githubusercontent.com/1911039/105357526-159e5c80-5c49-11eb-9a20-25d1ee2038f1.png">

I can render this if the new express_ref macros are escaped in the source code (as just implemented in https://github.com/metanorma/metanorma-standoc/issues/416); whatever is in the Express source, the hyperlinked keywords need to appear like this:

````
TYPE as_name_attribute_select = SELECT BASED_ON {{{<<express-schema:basic_attribute_schema.name_attribute_select, name_attribute_select>>}}} WITH 
   ({{{<<express-schema:action_schema.action_request_solution, action_request_solution>>}}});
END_TYPE; 
````

Note also that the original is selective about what is hyperlinked: no term defined in the current subclause is hyperlinked (in effect, that means no names of entities, attributes.

Somehow, the Express sourcecode generation needs to have already preprocessed all the Express files that will be passed to Lutaml, and extracted all the schema names and their children, and annotated the sourcecode with them. And the keywords need to be identified with lexical scope, in case of ambiguity, with an understanding of Express schema inheritance.

I assumed I could take care of this by identifying keywords and post-processing the HTML output of the collection; but since this is expected to appear in PDF as well, and since it seems that the Express needs to be parsed semantically to resolve ambiguity, I can't do it.

Since the previous ISO 10303 realisation has actually done this, it clearly is automatable, and the team behind it might need to be consulted.

**Comment by opoudjis** [comment]
Needed for https://github.com/lutaml/expressir/issues/54

**Comment by ronaldtse** [comment]
It can be done by these steps:
1. make the Expressir parse tree available in Metanorma
2. During the metanorma run, make note in the expressir tree nodes on where each EXPRESS element is documented (associate the metanorma anchor with the EXPRESS element)
3. Process the EXPRESS snippets in Metanorma using the Expressir parse tree so it Expressir can add links in the snippet for Metanorma.

**Comment by zakjan** [comment]
Escape mark output could be triggered with another option for the formatter

```
Expressir::ExpressExp::Formatter.format(node, { escape_ids_for_hyperlinks: true })
```

**Comment by zakjan** [comment]
Excuse me, the above was only a suggestion how a formatter could support changing output for a particular use case. It's not implemented yet.

Maybe even better could be to subclass the formatter and override [format_expressions_simple_reference](https://github.com/lutaml/expressir/blob/master/lib/expressir/express_exp/formatter.rb#L845-L847) method to return ids with cross-references. This would allow to have the subclass directly in a repo that has such use case.

**Comment by zakjan** [comment]
Solutions above assume that only parsed ids with model representation needs to be overridden.

@ronaldtse Do you know if also ids appearing in remark content needs to be overridden? These don't have any model representation, because remark content is a free-form text. This would need a different solution, based on matching known ids in the source string.

**Comment by w00lf** [comment]
@ronaldtse  @zakjan after some extended research i can say for sure that we cant use any objects inside liquid templates, so the approach with a custom formatted filter: {{ node.sourcecode | format }} won't work. The first call to the object will execute its `to_liquid` method and if it returns anything except of String, Number, Hash or Array it will be discarded and the chain will stop. We need to have the direct method on expressir object that I can serialize in lutaml into the hash attribute. Something like `schema.node.formatted_sourcecode`

**Comment by w00lf** [comment]
Because we also need to cross-link all elements I propose to also introduce dependency injection `formatter` - this object will be used to format sourcecode when I call `schema.node.formatted_sourcecode`. That way I can inherit from the default formatter and override its `format_expressions_simple_reference` method to introduce crosslinks. Usage from code can be like this: `repo = Expressir::ExpressExp::Parser.from_exp(input_file, formatter: MyCustomFormatter)`

**Comment by zakjan** [comment]
Thanks for the research. It's unfortunate that passing custom objects into Liquid is not supported. Where does adding formatter reference and methods to model classes help then?

Anyway, it depends whether ids in remarks content should also be formatted as hyperlinks or not. @ronaldtse Could you clarify this? If yes, it would need #49 + match for known ids in original source instead.

**Comment by w00lf** [comment]
>Where does adding formatter reference and methods to model classes help then?

Yes, I used the wrong term, we need an instance variable called `sourcecode`, lutaml will automatically  serialize it and add to the liquid context. The formatter reference is needed in order to overwrite `format_expressions_simple_reference` method from lutaml, replace it with the full reference path.

**Comment by ronaldtse** [comment]
Now I understand what @w00lf wanted, which is correct.

In order to format the source code with links, he’s planning to use the Expressir parse tree where a custom formatter can provided, so the appropriate code bits can be formatted in the way desired. 

This means that the original “formatted_sourcecode” method is supposed to be passed a “PlainFormatter” where everything is formatted as plain text. 

regarding @zakjan ‘s comments
- I don’t think Expressir needs to know where the hyperlinks are created. 
- The “id” of an object probably doesn’t need hyperlinks, but not sure why this makes any difference

**Comment by w00lf** [comment]
> Now I understand what @w00lf wanted, which is correct.
> 
> In order to format the source code with links, he’s planning to use the Expressir parse tree where a custom formatter can provided, so the appropriate code bits can be formatted in the way desired.
> 
> This means that the original “formatted_sourcecode” method is supposed to be passed a “PlainFormatter” where everything is formatted as plain text.
> 
> regarding @zakjan ‘s comments
> 
> * I don’t think Expressir needs to know where the hyperlinks are created.
> * The “id” of an object probably doesn’t need hyperlinks, but not sure why this makes any difference

No, the approach with `formatted_sourcecode` method will not work, it needs to be an instance attribute, we cant call any methods from liquid

**Comment by ronaldtse** [comment]
Can’t we implement this in a custom filter and place this code in LutaML?

**Comment by w00lf** [comment]
> Can’t we implement this in a custom filter and place this code in LutaML?

No, unfortunately, the custom filter approach will not work. I have tried a number of approaches to do that: custom wrappers, liquid Drops - none of them supports working with the original objects inside the liquid context. With custom filters, you cant just use `object.attribute | custom_filter` - in this case, the first call to  `object` will trigger its `to_liquid` method and after that liquid is expecting that this call will return simple objects: `Array, String, Hash` if it returns anything else it will be discarded.

**Comment by zakjan** [comment]
It's unfortunate that there is this incompatibility with Liquid, I didn't expected it. Passing formatter instance to parser could indeed solve this particular usecase. However, I'd be careful about it, because it would prevent passing parsed model from another source outside of LutaML control, e.g. deserialized from cache (#49).

I have an idea to discuss. How about changing the model from classes to hashmaps? The classes mostly act as hashmaps anyway. There are a few methods, but they could be extracted to a separate class. Then the approach with custom filter would work, right? Also, it would support better interoperability between tools, hashmaps could be exactly the format in external cache. I'll go through the classes to see the impact.

**Comment by zakjan** [comment]
Or instead of changing from classes to hashmaps entirely, there could be `to_map` method on all classes, which would call `to_map` on their children as well.

**Comment by w00lf** [comment]
> Or instead of changing from classes to hashmaps entirely, there could be `to_map` method on all classes, which would call `to_map` on their children as well.

We already doing that in lutaml: https://github.com/lutaml/lutaml/blob/master/lib/lutaml/express/lutaml_path/document_wrapper.rb#L26, https://github.com/lutaml/lutaml/blob/master/lib/lutaml/lutaml_path/document_wrapper.rb#L28

**Comment by zakjan** [comment]
Yes, in the current state, LutaML prepares the model for presentation, including calling Formatter wherever it's needed, so that it can be used in the templates. I can see Formatter is already called there, so this approach works, right?

However, it needs LutaML to have knowledge about the model structure. Is it fine, or would it be better to keep the model opaque to LutaML?

I'll probably need to implement export/import to/from hashmap anyway, for the external cache usecase.

**Comment by ronaldtse** [comment]
I've discussed this with @w00lf and there are two ways to do it:

1. `Expressir.fomatter = MyCustomFormatter`. Jan uses `Expressir.fomatter` in order to create formatted source code and LutaML has `MyCustomFormatter` which will have access to the metnorma express cache. This we only pass around hashes in Liquid.

2. Use Liquid Drops (which can carry any data internally, but can only return typical Liquid values like Strings/Hashes). Both `expressir_load xxx` and `mydrop xxx` return Drops, and `expressir_format_with_hyperlinks` processes a Drop.
```
{% assign mydrop = expressir_load "context" %}
{ mydrop "action_schema" | expressir_format_with_hyperlinks }
```

@w00lf is going to try to get the first approach working because the second is cumbersome.

Approach:
- Just keep in mind that after this we also have to do it for XMI/UML, but we can tweak the process later too.
- The less "magic" the better, the more "configuration" user can set the better.

Thoughts:
- The real reason why we're having this problem: it's because we are using Liquid separately from the document. Their contexts are not integrated.

**Comment by opoudjis** [comment]
Discussion with Jan:

>>> crossreferencing - the fastest for now would be if Miki calls Formatter for all objects where needed, using a subclassed Formatter with overridden method that outputs referenced ids (`format_expressions_simple_reference`). However, that would add more knowledge of model structure to LutaML, and I don't know if that's preferred or not. If not, we need to have a decision about the new approach.

>> Jan: We absolutely do need more knowledge about the Express model for the crossrefs to work, which is why you're pinged. It may be that you preprocess the model and pass a file to Lutaml giving the structure, I don't know

>> There does need to be a decision, yes. And it is the lowest priority, so you can take your time to come up with a good solution.

> I know, I should create docs for the model structure. Mostly I followed conventions in the spec or eengine. Currently you can see the structure by looking into the model source or the tests

**Comment by opoudjis** [comment]
> I'm about to implement a custom formatter to support this functionality. It's going to need a few underlying changes, to be able to look up elements in both downwards and upwards direction in the tree. Could you help to answer the following questions, or point me to more samples?

Samples: 

https://github.com/metanorma/iso-10303-smrl/tree/master/reference-docs/N10480_SMRL_v8_rc5

Check out, and navigate to: reference-docs/N10480_SMRL_v8_rc5/data/resource_docs/fundamentals_of_product_description_and_support/sys/contents.htm

fundamentals_of_product_description_and_support is ISO-10303-41, the document we are reproducing

**Comment by opoudjis** [comment]
> - format of hyperlinks should be {{{<<express-schema:fully-qualified-path-starts-with-schema-id,text-in-source-code>>}}}?

Updated, it is now `{{{express:fully-qualified-path-starts-with-schema-id,text-in-source-code>>}}}` (so different namespace)

**Comment by opoudjis** [comment]
> - as_name_attribute_select in your sample - don't hyperlink because it's the declaration itself, right? All other ids should be hyperlinked, no matter if they reference an element in the same schema or in another schema or in a different file?

That is my understanding, yes. So:

````
ENTITY action;
  name : label;
  description : OPTIONAL text;
  chosen_method : action_method;
DERIVE
  id : identifier := get_id_value(SELF);
WHERE
  WR1: SIZEOF(USEDIN(SELF, 'BASIC_ATTRIBUTE_SCHEMA.' + 'ID_ATTRIBUTE.IDENTIFIED_ITEM')) <= 1;
END_ENTITY;
````

Nothing to the left of a colon is hyperlinked, because they're all defined in that clause (attribute names, wheres). Everything right of colon (types) is hyperlinked, including both action_method in the current schema, and label and identifier in other schemas in the same document.

**Comment by opoudjis** [comment]
> - SELF\Shape_element.element_name[1:13] in data/modules/wire_and_cable_design_connectivity/arm.exp - hyperlink SELF\Shape_element.element_name[1:13] or SELF\Shape_element.element_name or Shape_element.element_name or element_name?

Don't understand the question

**Comment by opoudjis** [comment]
> - all ids should be hyperlinked, no matter of the target element type, or only some of them? 

It does seem all of them, except that the body of functions (as opposed to its parameters) is not hyperlinked.

Note that

````
WR1: acyclic_action_directive_relationship(SELF, [related], 'ACTION_SCHEMA.ACTION_DIRECTIVE_RELATIONSHIP');
````

doesn't have `acyclic_action_directive_relationship` hyperlinked; I suspect that might well be a technical failing of their hyperlinking system, not recognising functors before parentheses.

**Comment by zakjan** [comment]
> > SELF\Shape_element.element_name[1:13] in data/modules/wire_and_cable_design_connectivity/arm.exp - hyperlink SELF\Shape_element.element_name[1:13] or SELF\Shape_element.element_name or Shape_element.element_name or element_name?

> Don't understand the question

What's the expected output for combined references such as `SELF\Shape_element.element_name[1:13]`?

Based on the samples, it seems that it should be `SELF\{{{<express:Shape_property_assignment_arm.Shape_element,Shape_element>}}}.element_name[1:13]`, i.e. hyperlinking the first part of the reference after SELF. Could you confirm this, or is there another more preferred format? In any case I'll need to restructure the reference classes to support this, so we can choose what's the best.

**Comment by zakjan** [comment]
> It does seem all of them, except that the body of functions (as opposed to its parameters) is not hyperlinked.

This would mean skipping all kinds of local variables, is it correct?

**Comment by zakjan** [comment]
It seems that ids with `\` are used only in function bodies or expressions (e.g. where rules). The syntax is described in the spec 12.7.4 Group references.

![Screen Shot 2021-02-11 at 9 56 32](https://user-images.githubusercontent.com/173585/107617210-c946ab00-6c4f-11eb-8a1e-a11d53ff0cd8.png)

**Comment by opoudjis** [comment]
I have no means of confirming this, because I don't know anything more than you do about the samples. I suggest doing the maximum that is easy to hyperlink (but no local variables, you're right—they would be defined within the clause presenting the function anyway). We can always get feedback if more are needed.

**Comment by zakjan** [comment]
Reopening for feedback and final improvements

**Comment by zakjan** [comment]
Infinite recursion caused by cyclic reference between product_property_definition_schema and product_property_representation_schema is fixed.

TODO: support renamed references:

```
REFERENCE FROM schema1 (item AS item1);
REFERENCE FROM schema2 (item AS item2);
```

**Comment by zakjan** [comment]
Support for hyperlinking renamed references is implemented.

**Comment by zakjan** [comment]
Releasing as 0.2.15
