### ISSUE TITLE
Segfaults in C++ native extension

### ISSUE THREAD

**Issue by zakjan** [lutaml/expressir#74]
Opening this issue to summarize the state of C++ native extension stability.

During the initial implementation of C++ native parser, there used to be frequent segfaults. In that time, I decreased segfault frequency to none on my machine by reordering of Ruby code, so that it always first extracts values from native classes to Ruby variables, and only then uses them for further processing. It's strange, but it helps, as if it introduces some sort of a sync barrier (if we were in a multi-threaded code, but we're not). It might be caused by Rice or Ruby GC, but I couldn't find the real cause yet.
 https://github.com/lutaml/expressir/blob/37015c9bffc95abd05147df533107a85dbe03e07/lib/expressir/express_exp/visitor.rb#L1916-L1948

There is a note to avoid retaining any references to ANTLR4 native classes in [antlr4-native-rb](https://github.com/camertron/antlr4-native-rb#caveats), otherwise it leads to segfaults. I think that I'm following this correctly, but apparently there is more to that. In a [discussion](https://github.com/camertron/antlr4-native-rb/pull/5#issuecomment-749794632) with the author, he's also not sure about the real cause.

Based on https://github.com/metanorma/annotated-express/pull/70#issuecomment-800842128 segfaults still occur. Rarely, but they do. This needs more investigation. If a segfault occurs, currently just re-run the command.

**Comment by ronaldtse** [comment]
Any thoughts @CAMOBAP ? I am on macOS using the precompiled version. It only happened once to me...

**Comment by CAMOBAP** [comment]
@ronaldtse as far as I understood we are talking about https://github.com/metanorma/annotated-express/pull/70#issue-594401153 right?

If this happens randomly, I'm also a bit confused because as @zakjan already mentioned we aren't in multi-threaded environment.

@ronaldtse could you please confirm your steps to reproduce the issue (even if it happens only once) including platform and gem version

**Comment by ronaldtse** [comment]
I just ran `bundle exec metanorma site generate`.

Version info:

```
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/expressir-0.2.21-x86_64-darwin/lib/expressir/express_exp/visitor.rb:432: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
```

You can see the full trace in #70 .

[Gemfile.lock.zip](https://github.com/lutaml/expressir/files/6165671/Gemfile.lock.zip)

**Comment by ronaldtse** [comment]
@maxirmx this segfault is indeed challenging to our release pipeline, I just encountered it today. Would you have time to do this? Thanks!

**Comment by maxirmx** [comment]
@ronaldtse
From the discussions in this and other issues I got an impression that there are some references to  ANTLR4 native variables that are used accross calls to Ruby code.  Such instances are local variables (i.e. allocated on stack) and passed by pointer.   Result should be unpredictable but it is an error, of course. 

The issue is that I do not see where it happens.  Possibly 'everywhere' and it is a fundamental design flaw.

**Comment by ronaldtse** [comment]
@maxirmx the Expressir gem's parser code is generated from the ANTLR grammar using https://github.com/camertron/antlr4-native-rb , so the pointer reference issues are likely there. Could you investigate in that direction?

**Comment by ronaldtse** [comment]
@maxirmx The segfault seems reliably reproduced in this build with Ruby 2.7: https://github.com/lutaml/expressir/runs/5721221032?check_suite_focus=true

Maybe that is a good place to start investigation.

**Comment by maxirmx** [comment]
I made several changes that improved stability as follows:

- ```parse.rb -- self.from_file, self.from_files```
parse, syntax, visitor methods return complex tree structures created in netive (C++) extension
visit method references nodes and leaves of this structures but it is totally untransparent for Ruby GarbageCllector
so in this class we keep those C++ structure marked for GC so they are not freed 

- upgraded antlr to version 4.9.2  It shall resolve an issue with th order of static constructors  (https://github.com/antlr/antlr4/commit/0d0e7b44c4fd05e60618f1ce65ca694336cc26e3)

- Changed ``ContextProxy``` implementation so that getParent, getChildren methods return 'detached' objects  that can be safely freed by Ruby Garbage collector

However, there is other issue (or issues) out there.   It happens very rarely and is a ri test failure, not crash.  Also overal CI/testing dows not look very robust as I described in #113

**Comment by maxirmx** [comment]
https://github.com/camertron/antlr4-native-rb/issues/9

**Comment by maxirmx** [comment]
Although the extension _looks_ more stable, there is (are) issue(s) that cause abnormal terminations. It looks like the problem is related to compaction (good explanation is here: https://alanwu.space/post/check-compaction/)  
Running 'verify_compaction_references' results in weird issues so it is not easy to track either.
 
Something very similar was researched and not fixed  in Rice as discussed here: https://github.com/jasonroelofs/rice/pull/159

**Comment by maxirmx** [comment]
Expressir implements a method to access antlr token stream from Ruby.
This method (Parser.tokens in Ruby; ParserProxy::getTokens in C++) is generates on top of the source created by antlr4-native gem. getTokens returns Ruby array containing direct references to antlr objects and it is an issue.
When Ruby releases the array it also attempts to release all its members since there is no information of other references to said members.
